name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - main
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - 'draft/**'
      - yarn.lock

# 任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build
        run: yarn install && yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: docs/.vuepress/dist